pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - merged
      - label=needs-backporting
    actions:
      backport:
        branches:
          - stable
      label:
        remove: [needs-backporting]
        
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - base=master
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: smart
      label:
        remove: [ready-to-merge]
      delete_head_branch: {}

  
  - name: automatic merge cherrypick on stable
    conditions:
      - status-success=Travis CI - Pull Request
      - base=stable
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}