pull_request_rules:
        
  - name: automatic merge master on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - base=master
      - label=merge-when-green
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        strict: smart

  - name: clean-up after merge
    conditions:
      - merged
    actions:
      label:
        remove: [merge-when-green]
      delete_head_branch: {}

  - name: backport patches to 1.0.x branch
    conditions:
      - base=master
      - merged
      - label=backport-1.0.x
    actions:
      backport:
        branches:
          - 1.0.x
      label:
        remove: [backport-1.0.x]

  - name: backport patches to 1.1.x branch
    conditions:
      - base=master
      - merged
      - label=backport-1.1.x
    actions:
      backport:
        branches:
          - 1.1.x
      label:
        remove: [backport-1.1.x]
  
  - name: automatic merge for mergify bot (backports)
    conditions:
      - status-success=Travis CI - Pull Request
      - author=mergify[bot]
    actions:
      merge:
        method: merge
        strict: true

  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
      add: ["work-in-progress"]