pull_request_rules:
        
  - name: automatic merge master on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - base=master
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - label!=work-in-progress
    actions:
      merge:
        method: squash
        strict: smart

  - name: backport patches to 1.0.x branch
    conditions:
      - base=master
      - merged
      - label=backport-1.0.x
    actions:
      backport:
        branches:
          - 1.0.x
      label:
        remove: [backport-1.0.x]

  - name: backport patches to 1.1.x branch
    conditions:
      - base=master
      - merged
      - label=backport-1.1.x
    actions:
      backport:
        branches:
          - 1.1.x
      label:
        remove: [backport-1.1.x]

  - name: clean-up after merge
    conditions:
      - base=master
      - merged
    actions:
      label:
        remove: [ready-to-merge]
      delete_head_branch: {}
  
  - name: automatic merge for mergify bot cherrypicks on 1.1.x
    conditions:
      - status-success=Travis CI - Pull Request
      - author=mergify[bot]
      - base=1.1.x
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}

  - name: automatic merge for mergify bot cherrypicks on 1.0.x
    conditions:
      - status-success=Travis CI - Pull Request
      - author=mergify[bot]
      - base=1.0.x
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}